- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
