- name: Set misc kernel parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-override.conf
    state: present
    reload: true
  loop:
    - { key: fs.inotify.max_user_watches, value: 524288 }
    - { key: net.ipv4.ip_forward, value: 1 }
    - { key: net.ipv6.conf.all.forwarding, value: 1 }

- name: Disable DNSStubListener in systemd-resolved
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: 'DNSStubListener=no'
    state: present
  notify: Restart systemd-resolved


- name: Add Tailscale APT repository
  become: true
  ansible.builtin.deb822_repository:
    name: tailscale
    uris: https://pkgs.tailscale.com/stable/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: https://pkgs.tailscale.com/stable/ubuntu/resolute.noarmor.gpg
    state: present
  notify: Update APT cache

- name: Flush handlers immediately
  ansible.builtin.meta: flush_handlers

- name: Install APT packages from list 'apt_ubuntu_srv'
  become: true
  ansible.builtin.apt:
    name: "{{ apt_ubuntu_srv }}"
    state: latest
  when: apt_ubuntu_srv is defined

- name: Install Homebrew packages from list 'linuxbrew_ubuntu_srv'
  community.general.homebrew:
    name: "{{ linuxbrew_ubuntu_srv }}"
    state: latest
    force_formula: true
  when: linuxbrew_ubuntu_srv is defined

- name: Install Go packages from list 'go_ubuntu_srv'
  ansible.builtin.shell:
    # Custom GOPATH is needed when bootstraping (pre ~/.zshenv population).
    cmd: GOPATH={{ path_golang | quote }} go install {{ item | quote }}
  loop: "{{ go_ubuntu_srv }}"
  when: go_ubuntu_srv is defined
  changed_when: false

- name: Install Pip packages from list 'pip_ubuntu_srv'
  ansible.builtin.pip:
    name: "{{ pip_ubuntu_srv }}"
    state: latest
    executable: "{{ pip_exec }}"
    extra_args: "{{ pip_args }}"
  when: pip_ubuntu_srv is defined


- name: Create AdGuard directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop:
    - /srv/adguard
    - /srv/adguard/conf
    - /srv/adguard/work
  tags: adguard

- name: Deploy AdGuard container
  become: true
  containers.podman.podman_container:
    name: adguard
    hostname: "{{ hostname }}-adguard"
    image: docker.io/adguard/adguardhome
    ports:
      - 53:53/tcp
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
    mount:
      - type=bind,source=/srv/adguard/conf,target=/opt/adguardhome/conf
      - type=bind,source=/srv/adguard/work,target=/opt/adguardhome/work
    env:
      TZ: Europe/Stockholm
    cap_add:
      - net_bind_service
    cap_drop:
      - all
  tags: adguard

- name: Generate systemd unit file for AdGuard container
  become: true
  containers.podman.podman_generate_systemd:
    name: adguard
    no_header: true
    dest: /etc/systemd/system
    restart_policy: always
  tags: adguard

- name: Ensure AdGuard container is started and enabled
  become: true
  ansible.builtin.systemd:
    name: container-adguard
    enabled: true
    state: started
    daemon_reload: true
  tags: adguard


- name: Create Jellyfin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0755"
  loop:
    - /srv/jellyfin
    - /srv/jellyfin/cache
    - /srv/jellyfin/config
  tags: jellyfin

- name: Deploy Jellyfin container
  containers.podman.podman_container:
    name: jellyfin
    hostname: "{{ hostname }}-jellyfin"
    image: docker.io/jellyfin/jellyfin
    ports:
      - 7359:7359/udp
      - 8096:8096/tcp
    mount:
      - type=bind,source=/media/external,target=/media,ro=true
      - type=bind,source=/srv/jellyfin/config,target=/config
      - type=bind,source=/srv/jellyfin/cache,target=/cache
    env:
      TZ: Europe/Stockholm
  tags: jellyfin

- name: Generate systemd unit file for Jellyfin container
  containers.podman.podman_generate_systemd:
    name: jellyfin
    no_header: true
    dest: ~/.config/systemd/user
    restart_policy: always
  tags: jellyfin

- name: Ensure Jellyfin container is started and enabled
  ansible.builtin.systemd:
    name: container-jellyfin
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  tags: jellyfin


- name: Create misc nnn bookmarks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ path_nnn_bms }}/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: /media/external
      dest: media - external
