- name: Install APT packages from list 'apt_ubuntu_srv'
  become: true
  ansible.builtin.apt:
    name: "{{ apt_ubuntu_srv }}"
    state: latest
  when: apt_ubuntu_srv is defined

- name: Install Homebrew packages from list 'linuxbrew_ubuntu_srv'
  community.general.homebrew:
    name: "{{ linuxbrew_ubuntu_srv }}"
    state: latest
    force_formula: true
  when: linuxbrew_ubuntu_srv is defined

- name: Install Go packages from list 'go_ubuntu_srv'
  ansible.builtin.shell:
    # Custom GOPATH is needed when bootstraping (pre ~/.zshenv population).
    cmd: GOPATH={{ path_golang | quote }} go install {{ item | quote }}
  loop: "{{ go_ubuntu_srv }}"
  when: go_ubuntu_srv is defined
  changed_when: false

- name: Install Pip packages from list 'pip_ubuntu_srv'
  ansible.builtin.pip:
    name: "{{ pip_ubuntu_srv }}"
    state: latest
    executable: "{{ pip_exec }}"
    extra_args: "{{ pip_args }}"
  when: pip_ubuntu_srv is defined


- name: Create Jellyfin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  loop:
    - /media/external/Jellyfin
    - /media/external/Jellyfin/config
    - /media/external/Jellyfin/cache
  tags: jellyfin

- name: Deploy Jellyfin container
  containers.podman.podman_container:
    name: jellyfin
    hostname: "{{ hostname }}-jellyfin"
    image: docker.io/jellyfin/jellyfin
    restart_policy: unless-stopped
    ports:
      - "7359:7359/udp"
      - "8096:8096/tcp"
    mount:
      - "type=bind,source=/media/external,target=/media,ro=true"
      - "type=bind,source=/media/external/Jellyfin/config,target=/config"
      - "type=bind,source=/media/external/Jellyfin/cache,target=/cache"
  tags: jellyfin


- name: Create Tailscale directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  loop:
    - /var/lib/tailscale
  tags: tailscale

- name: Deploy Tailscale container
  containers.podman.podman_container:
    name: tailscale
    hostname: "{{ hostname }}-tailscale"
    image: docker.io/tailscale/tailscale:latest
    restart_policy: unless-stopped
    mount:
      - "type=bind,source=/var/lib/tailscale,target=/var/lib/tailscale"
    cap_add:
      - net_admin
      - net_raw
    env:
      TSIDP_STATE_DIR: "/var/lib/tailscale"
      TS_EXTRA_ARGS: "--advertise-exit-node"
  tags: tailscale


- name: Create misc nnn bookmarks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ path_nnn_bms }}/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: /media/external
      dest: media - external
