- name: Build image
  hosts: localhost
  gather_facts: false
  vars:
    docker_image: ubuntu:latest
    docker_base: ubuntu-base
  roles:
    - docker_build


- name: Bootstrap Ubuntu
  hosts: ubuntu-base
  gather_facts: false
  vars:
    docker_base: ubuntu-base
    user_name: "{{ lookup('env', 'USER') }}"
    user_group: "{{ lookup('env', 'USER') }}"
    user_groups: sudo
    user_shell: /bin/zsh
    user_password: $6$XyhyxtjslO9vryoo$xg3yUcbw91HobO8iSNY//ZKXuIajISEHLK0HinOcgwNG3WUlSQyLzOcdmeFvB2B0F0D2otmMYXW4ei2Y4wuaQ.
  roles:
    - docker_ubuntu

- name: Setup Ubuntu
  hosts: ubuntu-base
  vars:
    hostname: ubuntu-cnt
  roles:
    - common
    - linux_ubuntu
    - linux_ubuntu_cnt
    - common_nvim
    - common_post

- name: Snapshot container
  hosts: localhost
  gather_facts: false
  vars:
    docker_base: ubuntu-base
    docker_build: ubuntu-cnt
  roles:
    - docker_snapshot
