- name: Setup Ubuntu system - SRV
  hosts: ubuntu_srv
  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'linux_ubuntu', tags: 'linux_ubuntu' }
    - { role: 'linux_ubuntu_srv', tags: 'linux_ubuntu_srv' }
    - { role: 'common_nvim', tags: 'common_nvim' }
    - { role: 'common_post', tags: 'common_post' }
