- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
  become: true

- name: Install APT packages from list 'apt_ubuntu'
  ansible.builtin.apt:
    name: "{{ apt_ubuntu }}"
    state: latest
  become: true
  when: apt_ubuntu is defined

- name: Install Linuxbrew packages from list 'linuxbrew_ubuntu'
  community.general.homebrew:
    name: "{{ linuxbrew_ubuntu }}"
    state: latest
    force_formula: true
  when: linuxbrew_ubuntu is defined

- name: Install Go packages from list 'go_ubuntu'
  ansible.builtin.shell:
    # Custom GOPATH is needed when bootstraping (pre ~/.zshenv population).
    cmd: GOPATH={{ path_golang | quote }} go install {{ item | quote }}
  loop: "{{ go_ubuntu }}"
  when: go_ubuntu is defined
  changed_when: false

- name: Install Pip packages from list 'pip_ubuntu'
  ansible.builtin.pip:
    name: "{{ pip_ubuntu }}"
    state: latest
    executable: "{{ pip_exec }}"
    extra_args: "{{ pip_args }}"
  when: pip_ubuntu is defined


- name: Create file /etc/ssh/sshd_config.d/AllowUsers.conf
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart SSH
