- name: Install APT packages from list 'apt_ubuntu_tv'
  ansible.builtin.apt:
    name: "{{ apt_ubuntu_tv }}"
    state: latest
  become: true
  when: apt_ubuntu_tv is defined

- name: Install Homebrew packages from list 'linuxbrew_ubuntu_tv'
  community.general.homebrew:
    name: "{{ linuxbrew_ubuntu_tv }}"
    state: latest
    force_formula: true
  when: linuxbrew_ubuntu_tv is defined

- name: Install Go packages from list 'go_ubuntu_tv'
  ansible.builtin.shell:
    # Custom GOPATH is needed when bootstraping (pre ~/.zshenv population).
    cmd: GOPATH={{ path_golang | quote }} go install {{ item | quote }}
  loop: "{{ go_ubuntu_tv }}"
  when: go_ubuntu_tv is defined
  changed_when: false

- name: Install Pip packages from list 'pip_ubuntu_tv'
  ansible.builtin.pip:
    name: "{{ pip_ubuntu_tv }}"
    state: latest
    executable: "{{ pip_exec }}"
    extra_args: "{{ pip_args }}"
  when: pip_ubuntu_tv is defined


- name: Set AutomaticLogin in /etc/gdm3/custom.conf
  ansible.builtin.lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  loop:
    - regexp: '^#  AutomaticLoginEnable = true'
      line: AutomaticLoginEnable = true
    - regexp: '^#  AutomaticLogin = user1'
      line: AutomaticLogin = gleg

- name: Copy Port.conf to /etc/ssh/sshd_config.d
  ansible.builtin.copy:
    src: sshd_config.d/Port.conf
    dest: /etc/ssh/sshd_config.d/Port.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart SSH


- name: Create misc nnn bookmarks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ path_nnn_bms }}/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: /media/external
      dest: media - external
